name: Update CDN

on:
  push:
    branches:
      - main

jobs:
  update-cdn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy to CDN
      run: |
        # Copy your script to the GitHub Actions workspace
        cp nccff.js $pavillionJS

    - name: Commit and push to CDN repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add $pavillionJS@main/nccff.js
        git commit -m "Update CDN with latest changes"
        git push
